INSERT INTO botigues(ID, NOM, MAXQUADRES) VALUES (null, 'Botiga1', 20);
INSERT INTO botigues(ID, NOM, MAXQUADRES) VALUES (null, 'Botiga2', 25);
INSERT INTO botigues(ID, NOM, MAXQUADRES) VALUES (null, 'Botiga3', 23);
INSERT INTO botigues(ID, NOM, MAXQUADRES) VALUES (null, 'Botiga4', 15);

INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor1', 'Quadre1', 200, 1);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor2', 'Quadre2', 220, 1);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor3', 'Quadre3', 300, 2);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor4', 'Quadre4', 170, 3);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor5', 'Quadre5', 210, 1);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor6', 'Quadre6', 320, 4);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor7', 'Quadre7', 400, 2);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor8', 'Quadre8', 185, 3);
INSERT INTO quadres(ID, NOMAUTOR, NOMQUADRE, PREU, BOTIGAID) VALUES (null, 'Autor9', 'Quadre9', 335, 4);