DROP TABLE IF EXISTS BOTIGUES;

CREATE TABLE BOTIGUES(
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		NOM VARCHAR(255),
		MAXQUADRES INTEGER	
);

DROP TABLE IF EXISTS QUADRES;

CREATE TABLE QUADRES(
		ID INTEGER PRIMARY KEY AUTO_INCREMENT,
		NOMAUTOR VARCHAR(255),
		NOMQUADRE VARCHAR(255),
		PREU INTEGER,
		BOTIGAID INTEGER
);

ALTER TABLE QUADRES
ADD FOREIGN KEY (botigaid) REFERENCES botigues(id);